[package]
name = "xi-core-lib"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]
description = "Library module for xi-core"

[dependencies]
serde = "0.8"
serde_json = "0.8"
time = "0.1"

xi-rope = { path = "../rope", version = "0.1.1" }
xi-unicode = { path = "../unicode", version = "0.1.0" }
xi-rpc = { path = "../rpc", version = "0.1.0" }
fall = { git = "https://github.com/matklad/fall" }
fall-json = { git = "https://github.com/matklad/fall" }

[features]
avx-accel = ["xi-rope/avx-accel"]
simd-accel = ["xi-rope/simd-accel"]
